export const ROLE_CODES = [
  "SUPER_ADMIN",
  "ADMINISTRACION",
  "SISTEMAS",
  "ADMIN",
  "SUPERVISOR",
  "RECEPCION",
  "MEDICO",
  "DISPLAY",
] as const;

export type RoleCode = (typeof ROLE_CODES)[number];

export const PERMISSIONS = {
  USERS_MANAGE: "users:manage",
  USERS_READ_SELF: "users:read:self",
  SETTINGS_WRITE: "settings:write",
  AUDIT_READ: "audit:read",
  CATALOGS_WRITE: "catalogs:write",
  SCHEDULES_WRITE: "schedules:write",
  APPOINTMENTS_WRITE: "appointments:write",
  APPOINTMENTS_CALL_OWN: "appointments:call:own",
  DISPLAYS_MANAGE: "displays:manage",
  REPORTS_READ: "reports:read",
} as const;

export type PermissionCode =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Vacío: el personal entra solo con correo y contraseña. */
export const SENSITIVE_ROLES: readonly RoleCode[] = [];

export const ROLE_PERMISSIONS: Record<RoleCode, PermissionCode[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMINISTRACION: [
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.CATALOGS_WRITE,
    PERMISSIONS.SCHEDULES_WRITE,
    PERMISSIONS.REPORTS_READ,
  ],
  SISTEMAS: [
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.DISPLAYS_MANAGE,
    PERMISSIONS.SETTINGS_WRITE,
  ],
  ADMIN: [
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.CATALOGS_WRITE,
    PERMISSIONS.SCHEDULES_WRITE,
    PERMISSIONS.APPOINTMENTS_WRITE,
    PERMISSIONS.APPOINTMENTS_CALL_OWN,
    PERMISSIONS.DISPLAYS_MANAGE,
    PERMISSIONS.REPORTS_READ,
  ],
  SUPERVISOR: [
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SCHEDULES_WRITE,
    PERMISSIONS.APPOINTMENTS_WRITE,
    PERMISSIONS.APPOINTMENTS_CALL_OWN,
    PERMISSIONS.REPORTS_READ,
  ],
  RECEPCION: [
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.APPOINTMENTS_WRITE,
    PERMISSIONS.REPORTS_READ,
  ],
  MEDICO: [PERMISSIONS.USERS_READ_SELF, PERMISSIONS.APPOINTMENTS_CALL_OWN],
  DISPLAY: [],
};

export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  MFA_REQUIRED: "MFA_REQUIRED",
  MFA_ENROLLMENT_REQUIRED: "MFA_ENROLLMENT_REQUIRED",
  MFA_INVALID: "MFA_INVALID",
  RATE_LIMITED: "RATE_LIMITED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  OTP_INVALID: "OTP_INVALID",
  TURNSTILE_REQUIRED: "TURNSTILE_REQUIRED",
  ORIGIN_FORBIDDEN: "ORIGIN_FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_READY: "NOT_READY",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
} as const;
